// Manba: roadmap/Surxondaryo_mahalla_1kvm_yer_solig'i_2026.docx — Surxondaryo viloyati
// tumanlari va Termiz shahri kesimida mahallalar (MFY/SHFY) bo'yicha 2026-yil uchun
// jismoniy shaxslarning qishloq xo'jaligiga mo'ljallanmagan yerlariga 1 kv.m uchun yer
// solig'i stavkalari (tuman/shahar xalq deputatlari Kengashi qarorlari ilovalari asosida).
// Yuridik shaxslar uchun bu ma'lumot faqat 1 gektar (yirik uchastka) kesimida mavjud edi —
// platformamizdagi ijara uchastkalari esa m² miqyosida (5-2000 m², Tariff.minAreaM2/
// maxAreaM2) bo'lgani sabab, to'g'ridan-to'g'ri m² dagi ushbu stavka Sbaza va Kzona uchun
// ancha mos, aniq asos hisoblanadi (avvalgi versiya gektar bazasidan m²ga taxminiy
// (/10000) ayirib olingan edi — bu esa yillik stavkani oylik Sbaza sifatida ishlatishda
// noaniqlikka olib kelgan).
//
// Har bir tuman uchun baseRate — o'sha tumandagi eng ko'p uchraydigan (moda) stavka, ya'ni
// tumanning bazaviy (Kzona=1.0 ga yaqin) mahallalari darajasi. Mahalla (Zone) darajasidagi
// coefficient = mahalla_stavkasi / tuman_bazaviy_stavkasi.
//
// Ktuman (District.coefficient) — barcha tumanlar orasidagi eng past bazaviy stavkaga
// (2718.9 so'm/m²/yil — Boysun/Qiziriq) nisbatan normallashtirilgan.

export const REFERENCE_BASE_RATE = 2718.9;

export const DISTRICTS = [
  { code: 'TERMIZ_SH', name: 'Termiz shahri', baseRate: 5225.9 },
  { code: 'TERMIZ_T', name: 'Termiz tumani', baseRate: 4273 },
  { code: 'BOYSUN', name: 'Boysun tumani', baseRate: 2718.9 },
  { code: 'JARQORGON', name: "Jarqo'rg'on tumani", baseRate: 4413.8 },
  { code: 'SARIOSIYO', name: 'Sariosiyo tumani', baseRate: 3622.8 },
  { code: 'QIZIRIQ', name: 'Qiziriq tumani', baseRate: 2718.9 },
  { code: 'DENOV', name: 'Denov tumani', baseRate: 3602 },
  { code: 'UZUN', name: 'Uzun tumani', baseRate: 2817.7 },
  { code: 'QUMQORGON', name: "Qumqo'rg'on tumani", baseRate: 3361.5 },
  { code: 'BANDIXON', name: 'Bandixon tumani', baseRate: 2757.7 },
  { code: 'OLTINSOY', name: 'Oltinsoy tumani', baseRate: 3220.2 },
  { code: 'MUZRABOT', name: 'Muzrabot tumani', baseRate: 3019 },
  { code: 'SHEROBOD', name: 'Sherobod tumani', baseRate: 3260 },
  { code: 'SHORCHI', name: "Sho'rchi tumani", baseRate: 3700.5 },
  { code: 'ANGOR', name: 'Angor tumani', baseRate: 3090 },
];

export const ZONES_BY_DISTRICT = {
  TERMIZ_SH: [
    ['Abdulla Avloniy', 1.2], ['Abdurahmon Jomiy', 1.1], ['Alisher Navoiy', 1.0],
    ['Alpomish', 1.2], ['Amu sohillari', 1.0], ['Baynalmilal', 1.0],
    ["Bog'ishamol", 1.2], ["Bog'zor", 1.1], ["Bo'ston", 1.1],
    ['Chegara', 1.0], ["Do'stlik", 1.1], ['Eskishahar', 1.0],
    ['Farhod', 1.0], ["Gulira'no", 1.1], ['Guliston', 1.1],
    ['Jayhun', 1.2], ["Jo'yjangal", 1.1], ["Kattabog'", 1.1],
    ['Kokildorota', 1.0], ["Ma'rifat", 1.0], ['Majnuntol', 1.0],
    ['Manguzar', 1.0], ['Mehrobod', 1.0], ['Namuna', 1.2],
    ["Navro'z", 1.2], ['Nurli kelajak', 1.0], ['Pattakesar', 1.0],
    ['Saxovat', 1.2], ['Shifokor', 1.0], ['Shodlik', 1.2],
    ['Surxon sohili', 1.2], ["Temiryo'lchi", 1.0], ['Tinchlik', 1.1],
    ["Tuproqqo'rg'on", 1.2], ['Turon', 1.0], ["O'zbekiston", 1.2],
    ['Yulduz', 1.2],
  ],
  TERMIZ_T: [
    ['Ayritom MFY', 1.0], ['Amir Temur MFY', 1.0], ['AT-Termiziy MFY', 1.0],
    ['Bunyodkor MFY', 1.0], ['Gulbaxor MFY', 1.0], ['Guliston MFY', 1.0],
    ["Do'stlik MFY", 1.0], ["Jo'yjangal MFY", 1.0], ['Istiqlol MFY', 1.0],
    ['Qaxramon MFY', 1.0], ['Qoraxon MFY', 1.0], ['Quyoshli Yurt MFY', 1.0],
    ["Qo'ng'irot MFY", 1.0], ['Mustaqillik MFY', 1.0], ['Muxiddin Eshtemirov', 1.0],
    ["Navro'z MFY", 1.0], ['Namuna MFY', 1.0], ['Nurafshon MFY', 1.0],
    ['Nurli Diyor MFY', 1.0], ['Orol MFY', 1.0], ['Sabzipoya MFY', 1.0],
    ['Soliobod MFY', 1.0], ['Termiz MFY', 1.0], ['Uchqizil MFY', 1.0],
    ['Xalqobod MFY', 1.0], ['Sharof Rashidov', 1.0], ['Yangi Hayot MFY', 1.0],
    ['Yangiyer MFY', 1.0], ['Yangiobod MFY', 1.0], ['Kelajak MFY', 1.0],
  ],
  BOYSUN: [
    ['Urmonchi MFY', 1.0], ['Pulxokim MFY', 1.0], ['Sayrob MFY', 1.0],
    ['Tillokamar MFY', 1.0], ['Togchi MFY', 1.0], ['Tuda MFY', 1.0],
    ['Tuzbozor MFY', 1.0], ['Urta Machay MFY', 1.0], ['Chorchinor MFY', 1.0],
    ['Xujaidod MFY', 1.0], ['Sariosiyo MFY', 1.0], ['Chilonzor MFY', 1.0],
    ['Poygaboshi MFY', 1.0], ['Shirinobod MFY', 1.0], ['Shifobuloq MFY', 1.0],
    ['Shursoy MFY', 1.0], ['Yukori Machay MFY', 1.0], ['Xujabulgon MFY', 1.0],
    ['Pasurxi MFY', 1.0], ['Temir Darvoza MFY', 1.0], ['Mustakillik MFY', 1.0],
    ['Obi MFY', 1.0], ['Avlod MFY', 1.0], ['Arik-usti MFY', 1.0],
    ['Bibishirin MFY', 1.0], ['Bogibolo MFY', 1.0], ['Gaza MFY', 1.0],
    ['Darband MFY', 1.0], ['Daxnaijom MFY', 1.0], ["Dashtig'oz MFY", 1.0],
    ['Boshrabot MFY', 1.0], ['Duoba MFY', 1.0], ['Inkabod MFY', 1.0],
    ['Kizilnavr MFY', 1.0], ['Kosiblar MFY', 1.0], ['Kofrun MFY', 1.0],
    ['Kuchkak MFY', 1.0], ['Dexibola MFY', 1.0], ['Munchok MFY', 1.0],
  ],
  JARQORGON: [
    ['Paxtazavod MFY', 0.8], ['Oltintepa MFY', 1.0], ['Oktepa MFY', 1.0],
    ['Obodguzar MFY', 1.0], ['Oftobkurgon MFY', 1.0], ['Obi xayot MFY', 1.0],
    ['Navruz MFY', 1.0], ['Neftchilar MFY', 1.0], ['Namuna MFY', 1.0],
    ['Mustakillik MFY', 1.0], ['Mingchinor MFY', 1.0], ['Paxtaobod MFY', 1.0],
    ['Mexnat-roxat MFY', 1.0], ['Nurli diyor MFY', 1.0], ['Polvonlaryurti MFY', 1.0],
    ['Eskiqishloq MFY', 1.0], ['Sokchi MFY', 1.0], ['Mexnatobod MFY', 1.0],
    ['Yangiobod MFY', 1.0], ['Yangi usul MFY', 1.0], ['Yangi turmush MFY', 1.0],
    ['Yangi kishlok MFY', 1.0], ['Yangi arik MFY', 1.0], ['Porlokyulduz MFY', 1.0],
    ['Xujakishlok MFY', 1.0], ['Xayitobod MFY', 1.0], ['Urikli MFY', 1.0],
    ['Ulugbek MFY', 1.0], ['Uzumzor MFY', 1.0], ['Uzbekiston MFY', 1.0],
    ['Surxonsoxili MFY', 1.0], ['Xalkobod MFY', 1.0], ['Matonat MFY', 1.0],
    ['Kuldovli MFY', 1.0], ['Markaziysurxon MFY', 1.0], ['Maslaxattepa MFY', 1.0],
    ['A.Navoiy MFY', 1.0], ['Avlod MFY', 1.0], ['Beshbulok MFY', 1.0],
    ['Bobotog MFY', 1.0], ['Bobur MFY', 1.0], ['Boymokli MFY', 1.0],
    ['Gulxovuz MFY', 1.0], ['Gur-gur MFY', 1.0], ['Dam MFY', 1.0],
    ['Dexkonobod MFY', 1.0], ['Dustlik MFY', 1.0], ['Yoshlik MFY', 1.0],
    ['Janubkalkonlari MFY', 1.0], ['Jarkurgonminorasi MFY', 1.0], ['Guliston MFY', 1.0],
    ['Zartepa MFY', 1.0], ['Madaniyat MFY', 1.0], ['Jinjaktepa MFY', 1.0],
    ['Loykand MFY', 1.0], ['Kushtepa MFY', 1.0], ['Kunchikish MFY', 1.0],
    ['Korakursok MFY', 1.0], ['Korayontok MFY', 1.0], ['Kumkishlok MFY', 1.0],
    ['Korayogoch MFY', 1.0], ['Korabura MFY', 1.0], ['Yashnaobod MFY', 1.0],
    ['Kamar MFY', 1.0], ['Istiklol MFY', 1.0], ['Ismoiltepa MFY', 1.0],
  ],
  SARIOSIYO: [
    ['Alisher Navoiy MFY', 1.22], ['Aeroport MFY', 1.22], ['Afrosiyob MFY', 1.22],
    ['Anorzor MFY', 1.22], ['Billur MFY', 1.33], ["Bog'iobod MFY", 1.11],
    ["Bog'iston MFY", 1.0], ["Bog'isamarqand MFY", 1.0], ["Bog'ishamol MFY", 1.11],
    ["Bog'ishirin MFY", 1.11], ['Boysunobod MFY', 0.89], ['Buyrapusht MFY', 1.11],
    ['Chilonzor MFY', 0.89], ['Chosh MFY', 0.89], ['Daragiston MFY', 0.89],
    ['Diydor MFY', 1.11], ["Do'stlik MFY", 1.11], ['Ehtirom MFY', 1.11],
    ['Feruz MFY', 1.11], ['Galabutta MFY', 1.11], ['Gulobod MFY', 1.33],
    ['Jannatmakon MFY', 1.11], ['Karsh MFY', 0.89], ['Kelajaksari MFY', 1.0],
    ['Konchilar MFY', 1.0], ['Lochin MFY', 1.33], ['Lutfkor MFY', 1.33],
    ['Mirzo Ulugbek MFY', 1.33], ["Ma'dankon MFY", 1.11], ['Maland MFY', 0.89],
    ['Marjona MFY', 1.0], ['Mehr-shavqat MFY', 1.33], ['Neloba MFY', 1.22],
    ['Nilu MFY', 0.89], ['Niholzor MFY', 1.0], ['Nodirabegim MFY', 1.22],
    ['Nurbuloq MFY', 1.11], ['Nurobod MFY', 1.0], ["Sa'diy Sheroziy MFY", 1.33],
    ['Sangardak MFY', 1.11], ['Sarijar MFY', 1.0], ['Sebzor MFY', 1.0],
    ['Shabnam MFY', 1.0], ['Sharqyulduzi MFY', 1.33], ['Sharofobod MFY', 1.0],
    ['Shahriobod MFY', 1.33], ['Shirin MFY', 1.0], ['Shohqishloq MFY', 1.0],
    ['Shohjahon MFY', 1.33], ['Subxidam MFY', 0.89], ['Terakzor MFY', 1.33],
    ['Tortuli MFY', 1.11], ['Turmushobod MFY', 1.0], ['Xalqobod MFY', 1.11],
    ['Hamkorlik MFY', 1.11], ['Xonjiza MFY', 1.0], ['Xulkar MFY', 1.0],
    ['Xumoyun ( Xufar )MFY', 0.89], ['Xurshid MFY', 1.0], ['Yangihayot MFY', 1.33],
    ["Yoqutlibog' MFY", 1.33],
  ],
  QIZIRIQ: [
    ["Bog'bonlar yurti MFY", 1.14], ["Bog'iston MFY", 1.0], ['Buyuk kelajak MFY', 1.0],
    ['Gilambob MFY', 1.0], ['Gulzor MFY', 1.0], ['Gulobod MFY', 1.0],
    ["Do'stlik MFY", 1.14], ['Yetimqum MFY', 1.03], ['Zarbdor MFY', 1.0],
    ['Zarobod MFY', 1.0], ['Zartepa MFY', 1.0], ['Istara MFY', 1.0],
    ['Istiqlol MFY', 1.0], ['Karmaki MFY', 1.0], ['Qishloqozon MFY', 1.07],
    ['Qorasuv MFY', 1.0], ['Kunchiqish MFY', 1.07], ['Mustaqillik MFY', 1.0],
    ["Navro'z MFY", 1.0], ['Oqjar MFY', 1.07], ['Rabotak MFY', 1.14],
    ['Takiya MFY', 1.03], ['Tinchlik MFY', 1.0], ['Xalqobod MFY', 1.0],
    ['Xomkon MFY', 1.0], ['Shodlik MFY', 1.07], ['Yakka-terak MFY', 1.0],
    ['Yangi turmush MFY', 1.07], ['Yangi hayot MFY', 1.0], ['Yangikent MFY', 1.07],
    ['Yangiobod MFY', 1.01],
  ],
  DENOV: [
    ['AJomiy MFY', 1.16], ['Bahariston MFY', 1.16], ["Bog'i shamol MFY", 1.0],
    ["Bog'i Eram MFY", 1.0], ['Boginav MFY', 1.16], ['Buston MFY', 1.0],
    ['Buyuk zamin MFY', 1.0], ["Buyuk ipak yo'li MFY", 1.0], ['Buyuk kelajak MFY', 1.16],
    ['Vodiy MFY', 1.0], ['Guliston SHFY', 1.16], ['Guliston MFY', 1.0],
    ['Gulobod MFY', 1.0], ['Dahana MFY', 0.97], ['Dashti Chinor MFY', 0.97],
    ['Dunyotepa MFY', 1.0], ['Dustlik MFY', 1.0], ['Yoshlik MFY', 1.0],
    ['Jamatak MFY', 1.0], ['Z.M.Bobur MFY', 1.16], ['Zarafshon MFY', 1.0],
    ['Zartepa MFY', 1.0], ['Ibn Sino MFY', 1.16], ['Istiqbol MFY', 1.16],
    ['Istiqlol yulduzi MFY', 1.0], ['Qaytmas MFY', 1.0], ['Kata Qarshi MFY', 1.0],
    ['Qizilgul MFY', 1.0], ['Qiziljar MFY', 1.0], ['Qovunlisoy MFY', 1.0],
    ["Qorabog'tepa MFY", 1.0], ["Qorako'z MFY", 1.0], ['Qoraxon MFY', 1.0],
    ['Quyoshli yurt MFY', 1.16], ['Kuzichoqli MFY', 1.0], ['Kukabuloq MFY', 0.97],
    ['Kuhsor MFY', 0.97], ["Lag'monota MFY", 1.0], ['Lolazor MFY', 1.16],
    ['Lochin MFY', 1.0], ['Lupon MFY', 1.0], ['Mehnatobod MFY', 0.97],
    ['Mehr-oqibat MFY', 1.16], ['Mingbuloq MFY', 1.0], ['Minora MFY', 1.0],
    ['Muqumiy MFY', 1.0], ['Navbahor MFY', 1.0], ['Navnixol MFY', 1.0],
    ['Namozgoh MFY', 1.0], ['Namuna MFY', 1.0], ['Nuriston MFY', 1.16],
    ['Nurli manzil MFY', 1.16], ['Obod turmush MFY', 1.0], ['Obodon MFY', 1.0],
    ['Ozod MFY', 1.0], ['Oybarak MFY', 0.97], ['Oqtom MFY', 1.0],
    ["Oqqurg'on MFY", 1.0], ['Olovuddin MFY', 1.0], ['Ostona MFY', 1.0],
    ['Paxtakurash MFY', 1.0], ['Chashmasor MFY', 0.97], ['Sanoatchilik MFY', 1.16],
    ['Sebzor MFY', 1.0], ['Sina MFY', 0.97], ['Soxibkor MFY', 0.97],
    ['Sumbula MFY', 0.97], ['Surnaytepa MFY', 1.0], ['Surxon MFY', 1.0],
    ['Surxondiyor MFY', 1.0], ['Sufi Olloyor MFY', 1.16], ['Tasmasoy MFY', 1.0],
    ['Tinchlik MFY', 1.0], ['Totuvlik MFY', 1.16], ["O'zbekiston MFY", 1.0],
    ["O'zgarish MFY", 1.0], ["O'rikzor MFY", 1.16], ["O'rta qishloq MFY", 1.0],
    ['Ushor MFY', 0.97], ['Fayzli MFY', 1.0], ['Fayzobod MFY', 0.97],
    ["Xo'jaxalqi MFY", 1.0], ['Chagoniyon MFY', 1.0], ['Chambil MFY', 1.0],
    ['Chim MFY', 1.0], ['Chorgul MFY', 1.0], ['Chuqur qishloq MFY', 1.0],
    ['Chuntosh MFY', 1.0], ['Shamoli MFY', 1.0], ['Shahrinav MFY', 1.0],
    ['Elobod MFY', 1.0], ['Yurchi MFY', 1.0], ['Yangi Ariq MFY', 1.0],
    ['Yangi qishloq MFY', 1.0], ['Yangi Hazorbog MFY', 1.0], ['Yangikuch MFY', 1.0],
    ['Yangiobod MFY', 1.0], ['Yangihayot MFY', 1.16],
  ],
  UZUN: [
    ['Yoshlik MFY', 1.43], ['Xujakulsin MFY', 1.0], ['Baxoriston MFY', 1.14],
    ['Beshkapa MFY', 1.14], ["Bobotog' MFY", 1.0], ['Guliston MFY', 1.0],
    ['Dexkon MFY', 1.0], ["Dug'ob MFY", 1.0], ['Dustlik MFY', 1.29],
    ['Jiydabuloq MFY', 1.0], ['Surxon MFY', 1.14], ['Istiklol MFY', 1.0],
    ['Uzunkishlok MFY', 1.14], ['Ulankul MFY', 1.0], ['Urmanchi MFY', 1.0],
    ['Fayzobod MFY', 1.29], ['Fayzova MFY', 1.14], ['Xatib Kaxromon MFY', 1.0],
    ['Xursand MFY', 1.0], ['Uzbekiston MFY', 1.43], ['Chakar MFY', 1.14],
    ['Erkinlik MFY', 1.14], ['Yangi Kuch MFY', 1.14], ['Yangiobod MFY', 1.0],
    ['Yangiyul MFY', 1.29], ['Zarkamar MFY', 1.0], ['Yangiruzgor MFY', 1.29],
    ['Yangishaxar MFY', 1.29], ['Chinor MFY', 1.0], ['Tomchi MFY', 1.0],
    ['Yangixayot MFY', 1.14], ['Tojikobod MFY', 1.0], ['Karashik MFY', 1.29],
    ['Kichikjoncheka MFY', 1.29], ['Toltugay MFY', 1.0], ['Madaniy Turmush MFY', 1.14],
    ['Malandiyon MFY', 1.43], ['Mexnat MFY', 1.43], ['Mustakillik MFY', 1.0],
    ['Mustakillikning22yilligi MFY', 1.0], ['Navruz MFY', 1.0], ['Ittifoq MFY', 1.29],
    ['Obizarang MFY', 1.43], ['Obodyurt MFY', 1.0], ['Okostona MFY', 1.0],
    ['Okmachit MFY', 1.0], ['НурафшонМФЙ', 1.0], ['Serxarakat MFY', 1.0],
    ['Saxovat MFY', 1.0], ['Nurlikelajak MFY', 1.0], ['Paxlavon MFY', 1.0],
  ],
  QUMQORGON: [
    ['Bobolochin MFY', 1.06], ['Azlarsoy MFY', 1.0], ['Oktom MFY', 0.94],
    ['Beshkaxramon', 1.19], ['Neftchilar MFY', 1.0], ['Navbaxor MFY', 1.06],
    ['Mustakillik MFY', 1.0], ['Munchoktepa', 1.06], ['Mexrobod MFY', 1.13],
    ['Kuganli MFY', 0.94], ['Hunarmandlar MFY', 1.06], ['Kattakul MFY', 1.0],
    ['Qarsokli MFY', 1.06], ['Istiklol MFY', 1.0], ['Islomobod MFY', 0.94],
    ['Imomtepa MFY', 0.94], ['Joziba MFY', 1.0], ['Jiydali MFY', 1.13],
    ['Jarkishlok MFY', 1.0], ['Jaloir MFY', 1.06], ['Dustlik MFY', 1.13],
    ['Davlatsoy MFY', 1.0], ['Gultepa MFY', 1.13], ['Guliston MFY', 0.94],
    ['Galaba MFY', 1.06], ['Buston MFY', 0.94], ['Boymokli MFY', 1.0],
    ['Bogora MFY', 1.0], ['Bobotog MFY', 0.94], ['Pastxam MFY', 0.94],
    ['Paxtaobod MFY', 1.0], ['Nurli diyor MFY', 0.94], ['Surxonsoxili', 1.13],
    ["Arig'oshgan", 0.94], ['Arpapoya MFY', 1.0], ['Achamoyli MFY', 1.0],
    ['Arslonboyli MFY', 1.0], ['Yangikishlok', 1.0], ['Yangier MFY', 1.06],
    ['Yangi shaxar', 1.0], ['Yangi xayot', 0.94], ['Yangi obod MFY', 0.94],
    ['Saxovat MFY', 0.94], ['Elobod MFY', 1.06], ['Sherozi MFY', 1.0],
    ['Chukirli MFY', 0.94], ['Yangi avlod', 1.0], ['Hurriyat MFY', 1.0],
    ['Tayfang MFY', 0.94], ['Tebet MFY', 0.87], ['Yuksalish MFY', 0.94],
    ['Tuda MFY', 1.0], ['Uzbekiston5', 1.0], ['Ulugbek MFY', 1.13],
    ["Tug'on MFY", 1.0], ['Uyas MFY', 1.0], ['Xalaki MFY', 1.0],
    ['Xalkobod MFY', 1.0], ['Xujaqishlok', 1.0], ['Xujamulki MFY', 0.94],
    ['Umidnixollari', 1.0],
  ],
  BANDIXON: [
    ['Obodturmush MFY', 1.0], ['Obodyurt MFY', 1.0], ['Paxtakor MFY', 1.0],
    ['Polvontosh MFY', 1.0], ["Xo'jaipok MFY", 1.0], ["Urg'ulsoy MFY", 1.0],
    ['Farovon MFY', 1.0], ['Chinor MFY', 1.0], ['Obikor MFY', 1.0],
    ['Saroy MFY', 1.1], ['Navruz MFY', 1.0], ['Navbahor MFY', 1.0],
    ['Limonzor MFY', 1.01], ["Bag'rikeng MFY", 1.0], ['Bahoriston MFY', 1.08],
    ['Bektepa MFY', 1.1], ['Birdamlik MFY', 1.0], ['Bandixon MFY', 1.1],
    ['Zevar MFY', 1.0], ["Qaldirg'och MFY", 1.07], ['Quduqsoy MFY', 1.0],
    ["Gulbog' MFY", 1.07],
  ],
  OLTINSOY: [
    ['Jilibuloq MFY', 1.13], ['Madaniyat MFY', 1.0], ['Qusharcha MFY', 0.88],
    ['Qurama-1MFY', 1.0], ['Qumpaykal MFY', 1.0], ['Qoratepa MFY', 1.25],
    ['Qiziltepa MFY', 1.0], ['Karsagan MFY', 0.88], ['Ipoq MFY', 1.25],
    ['Zardaqul MFY', 0.88], ['Nurafshon MFY', 0.88], ['Jobu MFY', 0.88],
    ['Marmin MFY', 0.88], ['Jiyanbobo MFY', 1.13], ['Gulchechak MFY', 1.0],
    ['Gulobod MFY', 1.0], ['Guliston MFY', 1.25], ['Obod Vaxshivor MFY', 0.88],
    ['Katta Vaxshivor MFY', 0.88], ["Bo'ston MFY", 1.25], ['Botosh MFY', 1.0],
    ['Bibizaynab MFY', 1.0], ['Beshbolapaxlavon MFY', 1.0], ['Barkamolavlod MFY', 1.0],
    ['Shodlik MFY', 1.25], ["Dug'oba MFY", 1.0], ['Mingchinor MFY', 0.88],
    ['Qorliq MFY', 1.0], ['Muminqul MFY', 0.88], ['Yangiqurilish MFY', 1.0],
    ['Yangiarik MFY', 1.0], ['Yakka-tut MFY', 1.25], ['Ekraz MFY', 1.0],
    ['Shoxcha MFY', 1.0], ['Shakar-qamish MFY', 1.0], ['Chinor MFY', 0.88],
    ['Mirshodi MFY', 1.0], ['Xujaipok MFY', 0.88], ['Xidirsho MFY', 0.88],
    ['Xalqobod MFY', 1.0], ['Xayrandara MFY', 0.88], ['Chep MFY', 1.0],
    ['Mustaqillik-10 yilligi MFY', 1.0], ["Tog'ay Murod MFY", 0.88], ['Sohibkor MFY', 0.88],
    ['Sayrak MFY', 0.88], ['Paxlavon MFY', 0.88], ['Olmazor MFY', 1.0],
    ['Oqarbuloq MFY', 1.25], ['Ovchi MFY', 1.0], ['Obshir MFY', 0.88],
    ['Obodturmush MFY', 1.0], ['Navruz MFY', 1.0], ['Tuxtamish MFY', 0.88],
  ],
  MUZRABOT: [
    ['Alpomish MFY', 1.0], ['Anorzor MFY', 1.0], ['At Termiziy MFY', 1.0],
    ["Bog'i eram MFY", 0.93], ['Bodomzor MFY', 1.0], ["Buyuk ipak yo'li MFY", 1.0],
    ['Guliston MFY', 1.0], ['Gulobod MFY', 1.0], ['Darband MFY', 1.0],
    ['Dexqonobod MFY', 1.0], ['Duoba MFY', 1.0], ["Do'stlik MFY", 1.0],
    ["Yo'lchi MFY", 1.0], ['Madaniyat MFY', 1.0], ['Mexnatabod MFY', 1.0],
    ['Mexrigiyox MFY', 1.0], ['Moxiyat MFY', 0.93], ['Muzrabot darvoza MFY', 1.0],
    ['Mustaqillik MFY', 1.0], ['Navruz MFY', 1.0], ['Nurli xayot MFY', 1.0],
    ['Obi xayot MFY', 1.0], ['Obod turmush MFY', 1.0], ['Olmazor MFY', 1.0],
    ['Oriyat MFY', 1.0], ['Sopollitepa MFY', 1.0], ['Tong yulduzi MFY', 0.93],
    ['Fayziobod MFY', 0.93], ['Fidokor MFY', 1.0], ['Xalq yuli MFY', 0.93],
    ['Chegarachi MFY', 0.93], ['Shaffof MFY', 1.07], ['Yurtim jamoli MFY', 1.0],
    ['Yakkatol MFY', 1.0], ['Yangi diyor MFY', 1.0], ['Yangi xayot MFY', 1.07],
    ['Yangiyer MFY', 1.0],
  ],
  SHEROBOD: [
    ['Balxiguzar MFY', 1.0], ['Bahor MFY', 1.14], ["Bog'iobod MFY", 0.93],
    ['Boybuloq MFY', 1.0], ['Boyqishloq MFY', 0.93], ["Buyuk ipak yo'li MFY", 1.14],
    ['Vandob MFY', 0.95], ['Galaguzar MFY', 1.0], ["G'ambur MFY", 1.14],
    ['Guliston MFY', 0.95], ['Gulchinor MFY', 0.99], ["G'urjak 1 MFY", 1.0],
    ["G'urjak 2 MFY", 0.93], ["G'o'rin-Gilambob MFY", 1.0], ['Dehqonariq MFY', 1.0],
    ["Do'stlik MFY", 1.14], ['Yoshlik MFY', 1.14], ["Zarabog' MFY", 0.95],
    ['Istiqbol MFY', 0.93], ['Katta hayot MFY', 1.14], ["Kattabog' MFY", 1.0],
    ['Qizilolma MFY', 0.93], ['Qishloqbozor MFY', 1.0], ["Qorabog' MFY", 0.93],
    ['Qulluqsho MFY', 1.0], ["Qo'rg'on MFY", 1.14], ['Majnuntol MFY', 1.0],
    ['Mehnatobod MFY', 0.95], ['Mehrobod MFY', 0.93], ['Navbur MFY', 1.05],
    ['Nurtepa MFY', 1.05], ['Oyinli MFY', 0.99], ['Oqtepa MFY', 0.93],
    ['Oltinvoha MFY', 0.99], ['Poshxurt MFY', 0.93], ['Taroqli MFY', 1.0],
    ['Uzunsoy MFY', 0.94], ["Uch yog'och MFY", 0.95], ['Hakimobod MFY', 1.0],
    ["Xo'jaqiya 1 MFY", 1.05], ["Xo'jaqiya 2 MFY", 1.05], ["Xo'jgi MFY", 1.14],
    ["Chag'atoy MFY", 0.99], ["Chorbog' MFY", 0.95], ["Cho'yinchi MFY", 1.0],
    ["Chuqurko'l MFY", 0.99], ["Cho'mishli MFY", 0.99], ['Sherobod MFY', 0.99],
  ],
  SHORCHI: [
    ['Joyilma SHFY', 1.0], ['Zarbdor MFY', 1.0], ['Ibn-Sino MFY', 1.25],
    ['Kokaydi MFY', 1.0], ['Katta Savur SHFY', 1.0], ['Jarqishloq SHFY', 1.25],
    ['Konobod MFY', 1.0], ['Kakan MFY', 1.0], ['Yoshgayrat MFY', 1.0],
    ['Bobur MFY', 1.25], ['Guliston MFY', 1.0], ['Guzallik SHFY', 1.0],
    ['Bobotog MFY', 1.25], ['Baxshtepa-1MFY', 1.0], ['Baxshtepa MFY', 1.0],
    ['A.Navoiy MFY', 1.25], ["Garmakurg'on SHFY", 0.87], ['Koraarik MFY', 0.87],
    ['Dustlik MFY', 1.0], ['Kuklam MFY', 1.25], ['Buston MFY', 1.25],
    ['Kushtegirmon SHFY', 1.0], ['Kushon MFY', 1.0], ['Yangiarik MFY', 1.0],
    ['Yalti SHFY', 0.87], ['Yakkabog MFY', 1.0], ['Elbayon MFY', 0.87],
    ['Ezgulik MFY', 0.87], ['Egarchi MFY', 1.0], ['Bunyodkor MFY', 1.0],
    ['Shaldirok MFY', 1.0], ['Shakarkul MFY', 1.0], ['Xushchekka SHFY', 1.0],
    ['Xayrobod MFY', 1.25], ['Tula MFY', 1.25], ['Tolli MFY', 1.0],
    ['Sovjironbobo MFY', 1.0], ['Xurlik MFY', 1.0], ['Tamshush MFY', 0.87],
    ['Laylakxona MFY', 0.87], ['Navruz MFY', 1.25], ['Obodon MFY', 1.0],
    ['Tamaddun MFY', 1.0], ['Oynakul MFY', 0.87], ['Okkamar MFY', 1.0],
    ["Oqqo'rg'on MFY", 1.0], ['Ozod MFY', 0.87], ['Olatemir MFY', 1.0],
    ['Oliyximmat MFY', 1.0], ['Oftobmakon MFY', 1.0], ['Saksankapa MFY', 1.0],
    ['Saurtepa MFY', 1.0], ['Oktumshuk MFY', 1.0],
  ],
  ANGOR: [
    ['Bahor MFY', 1.0], ['Gilambob MFY', 1.0], ['Gulzor MFY', 1.0],
    ['Guliston MFY', 1.0], ['Qoraqir MFY', 1.0], ['Yangihayot MFY', 1.0],
    ['Zang Gilambob MFY', 1.0], ['Zartepa MFY', 1.0], ["Ilg'or MFY", 1.0],
    ['Qadimiy Angor MFY', 1.0], ['Kayran MFY', 1.0], ['Karvon MFY', 1.0],
    ['Kattaqum MFY', 1.0], ["Qorabog' MFY", 1.0], ['Qorasuv MFY', 1.0],
    ["Qo'shtegirmon MFY", 1.0], ['Madaniyat MFY', 1.0], ['Markaz MFY', 1.0],
    ['Navbahor MFY', 1.14], ["Navro'z MFY", 1.14], ['Navshahar MFY', 1.0],
    ["Do'stlik MFY", 1.0], ['Tallashqon MFY', 1.0], ["To'lqin MFY", 1.0],
    ["O'zbekiston MFY", 1.14], ["Ulug'bek MFY", 1.0], ['Farovon MFY', 1.0],
    ['Xomkon MFY', 1.0], ["Xo'janqon MFY", 1.0], ['Chinobod MFY', 1.0],
    ['Sharqguli MFY', 1.14], ['Yuqori Tallashqon MFY', 1.0], ['Yuqori Tallimaron MFY', 1.0],
    ["Yuqori Xo'jaqiya MFY", 1.0], ['Yangiobod MFY', 1.0], ['Yangiturmush MFY', 1.0],
  ],
};
